"use client";

import { useMemo, useState, useTransition } from "react";
import { AlertTriangle, CheckCircle2, FileSpreadsheet, Play, ShieldCheck, Upload, WandSparkles } from "lucide-react";
import { addCleaningRule, approveCleaningJob, createCleaningJob, resolveDuplicate, resolveIssue, runCleaningJob, toggleCleaningRule, updateFieldMapping } from "@/app/dashboard/cleaning/actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { CleaningIssue, CleaningJob, CleaningRule, FieldMapping, StagedRow } from "@/lib/cleaning/types";

type Duplicate = { id:string; staged_row_id:string; existing_product_id:string|null; duplicate_staged_row_id:string|null; score:number; reasons:string[]; resolution:string|null };
const targetFields = ["", "sku", "name", "category", "brand", "description", "barcode", "price", "cost", "currency", "stock_quantity", "unit", "quality_score", "status", "tags"];

export function CleaningWorkspace({ jobs, rules, selectedJob, rows, issues, duplicates }: { jobs:CleaningJob[]; rules:CleaningRule[]; selectedJob:CleaningJob|null; rows:StagedRow[]; issues:CleaningIssue[]; duplicates:Duplicate[] }) {
  const [message, setMessage] = useState("");
  const [pending, startTransition] = useTransition();
  const [mapping, setMapping] = useState<FieldMapping>(selectedJob?.field_mapping ?? {});
  const headers = useMemo(() => selectedJob ? Object.keys(selectedJob.field_mapping).length ? Array.from(new Set([...Object.keys(selectedJob.field_mapping), ...(selectedJob as CleaningJob & {source_headers?:string[]}).source_headers ?? []])) : ((selectedJob as CleaningJob & {source_headers?:string[]}).source_headers ?? []) : [], [selectedJob]);

  const invoke = (task:()=>Promise<unknown>) => startTransition(async()=>{try{await task();setMessage("Saved successfully");}catch(error){setMessage(error instanceof Error?error.message:"Action failed");}});

  return <div className="grid gap-6 xl:grid-cols-[330px_minmax(0,1fr)]">
    <aside className="space-y-5">
      <section className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-950">
        <h2 className="font-semibold">New cleaning job</h2><p className="mt-1 text-sm text-slate-500">Upload raw CSV data into an isolated staging area.</p>
        <form className="mt-4" action={(fd)=>invoke(async()=>{await createCleaningJob(fd);})}><label className="flex cursor-pointer flex-col items-center rounded-xl border border-dashed p-6 text-center hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-900"><Upload className="mb-2 h-5 w-5"/><span className="text-sm font-medium">Choose CSV</span><span className="mt-1 text-xs text-slate-500">Up to 25,000 rows / 10 MB</span><input className="hidden" type="file" name="file" accept=".csv,text/csv" onChange={(e)=>e.currentTarget.form?.requestSubmit()}/></label></form>
      </section>
      <section className="rounded-2xl border bg-white p-3 dark:border-slate-800 dark:bg-slate-950"><h2 className="px-2 py-2 text-sm font-semibold">Cleaning jobs</h2><div className="space-y-1">{jobs.map((job)=><a key={job.id} href={`/dashboard/cleaning?job=${job.id}`} className={`block rounded-xl px-3 py-3 text-sm ${selectedJob?.id===job.id?"bg-indigo-50 text-indigo-900 dark:bg-indigo-950 dark:text-indigo-100":"hover:bg-slate-50 dark:hover:bg-slate-900"}`}><div className="flex items-center justify-between gap-2"><span className="truncate font-medium">{job.name}</span><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] uppercase dark:bg-slate-800">{job.status}</span></div><div className="mt-1 text-xs text-slate-500">{job.total_rows} rows · {job.invalid_rows} issues</div></a>)}{!jobs.length&&<p className="px-3 py-8 text-center text-sm text-slate-500">No cleaning jobs yet.</p>}</div></section>
      <section className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-950"><h2 className="font-semibold">Cleaning rules</h2><div className="mt-3 space-y-2">{rules.map((rule)=><label key={rule.id} className="flex items-center justify-between rounded-lg border px-3 py-2 text-sm dark:border-slate-800"><span><strong>{rule.name}</strong><span className="block text-xs text-slate-500">{rule.field} · {rule.rule_type}</span></span><input type="checkbox" checked={rule.enabled} onChange={(e)=>invoke(()=>toggleCleaningRule(rule.id,e.target.checked))}/></label>)}</div><form action={(fd)=>invoke(()=>addCleaningRule(fd))} className="mt-4 space-y-2 border-t pt-4 dark:border-slate-800"><Input name="name" placeholder="Rule name" required/><div className="grid grid-cols-2 gap-2"><select name="field" className="h-10 rounded-xl border bg-transparent px-3 text-sm dark:border-slate-700">{targetFields.filter(Boolean).map((field)=><option key={field}>{field}</option>)}</select><select name="ruleType" className="h-10 rounded-xl border bg-transparent px-3 text-sm dark:border-slate-700"><option value="trim">Trim</option><option value="remove_extra_spaces">Remove extra spaces</option><option value="uppercase">Uppercase</option><option value="lowercase">Lowercase</option><option value="titlecase">Title case</option><option value="normalize_sku">Normalize SKU</option><option value="normalize_barcode">Normalize barcode</option><option value="coerce_number">Convert number</option><option value="default_value">Default value</option></select></div><Input name="defaultValue" placeholder="Default value (optional)"/><Button className="w-full" variant="secondary"><WandSparkles className="mr-2 h-4 w-4"/>Add rule</Button></form></section>
    </aside>

    <div className="min-w-0 space-y-5">
      {message&&<div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800 dark:border-blue-900 dark:bg-blue-950 dark:text-blue-100">{message}<button className="float-right" onClick={()=>setMessage("")}>×</button></div>}
      {!selectedJob?<section className="rounded-2xl border bg-white p-16 text-center dark:border-slate-800 dark:bg-slate-950"><FileSpreadsheet className="mx-auto h-10 w-10 text-slate-400"/><h2 className="mt-4 text-xl font-semibold">Select or create a cleaning job</h2><p className="mt-2 text-sm text-slate-500">Raw data remains isolated until it passes validation and review.</p></section>:<>
        <section className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-950"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">{selectedJob.name}</h2><p className="mt-1 text-sm text-slate-500">{selectedJob.source_filename} · {selectedJob.total_rows} staged rows</p></div><div className="flex gap-2"><Button disabled={pending} variant="secondary" onClick={()=>invoke(()=>runCleaningJob(selectedJob.id))}><Play className="mr-2 h-4 w-4"/>Run cleaning</Button><Button disabled={pending||selectedJob.status!=="review"} onClick={()=>invoke(()=>approveCleaningJob(selectedJob.id))}><ShieldCheck className="mr-2 h-4 w-4"/>Approve dataset</Button></div></div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4">{[["Total",selectedJob.total_rows],["Valid",selectedJob.valid_rows],["Invalid",selectedJob.invalid_rows],["Duplicates",selectedJob.duplicate_rows]].map(([label,value])=><div key={label} className="rounded-xl bg-slate-50 p-4 dark:bg-slate-900"><div className="text-xs uppercase text-slate-500">{label}</div><div className="mt-1 text-2xl font-bold">{value}</div></div>)}</div></section>

        <section className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-950"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Field mapping</h3><p className="mt-1 text-sm text-slate-500">Map source columns to the Maas product schema.</p></div><Button variant="secondary" onClick={()=>invoke(()=>updateFieldMapping(selectedJob.id,mapping))}>Save mapping</Button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{headers.map((header)=><label key={header} className="rounded-xl border p-3 text-sm dark:border-slate-800"><span className="mb-2 block truncate font-medium">{header}</span><select className="h-9 w-full rounded-lg border bg-transparent px-2 dark:border-slate-700" value={mapping[header]??""} onChange={(e)=>setMapping((current)=>({...current,[header]:e.target.value}))}>{targetFields.map((field)=><option value={field} key={field}>{field||"Ignore column"}</option>)}</select></label>)}</div></section>

        <section className="overflow-hidden rounded-2xl border bg-white dark:border-slate-800 dark:bg-slate-950"><div className="border-b px-5 py-4 dark:border-slate-800"><h3 className="font-semibold">Review queue</h3><p className="mt-1 text-sm text-slate-500">Preview cleaned values and validation status.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-900"><tr><th className="px-4 py-3">Row</th><th className="px-4 py-3">SKU</th><th className="px-4 py-3">Name</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Price</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y dark:divide-slate-800">{rows.map((row)=><tr key={row.id}><td className="px-4 py-3">{row.row_number}</td><td className="px-4 py-3 font-mono text-xs">{String(row.cleaned_data.sku??row.mapped_data.sku??"")}</td><td className="px-4 py-3">{String(row.cleaned_data.name??row.mapped_data.name??"")}</td><td className="px-4 py-3">{String(row.cleaned_data.category??row.mapped_data.category??"")}</td><td className="px-4 py-3">{String(row.cleaned_data.price??row.mapped_data.price??"")}</td><td className="px-4 py-3">{row.is_duplicate?<span className="text-amber-600">Duplicate</span>:row.is_valid?<span className="text-emerald-600">Valid</span>:<span className="text-red-600">Needs review</span>}</td></tr>)}</tbody></table></div>{!rows.length&&<div className="p-10 text-center text-sm text-slate-500">Run the cleaning job to populate the review queue.</div>}</section>

        {(issues.length>0||duplicates.length>0)&&<div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-950"><h3 className="flex items-center gap-2 font-semibold"><AlertTriangle className="h-4 w-4 text-amber-500"/>Validation issues</h3><div className="mt-4 space-y-3">{issues.map((issue)=><div key={issue.id} className="rounded-xl border p-3 text-sm dark:border-slate-800"><div className="font-medium">{issue.message}</div><div className="mt-1 text-xs text-slate-500">{issue.issue_type} · {issue.status}</div>{issue.status==="open"&&<div className="mt-3 flex gap-2"><button className="text-xs font-medium text-emerald-600" onClick={()=>invoke(()=>resolveIssue(issue.id,"fixed"))}>Mark fixed</button><button className="text-xs font-medium text-slate-500" onClick={()=>invoke(()=>resolveIssue(issue.id,"ignored"))}>Ignore</button></div>}</div>)}</div></section><section className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-950"><h3 className="flex items-center gap-2 font-semibold"><CheckCircle2 className="h-4 w-4 text-indigo-500"/>Duplicate candidates</h3><div className="mt-4 space-y-3">{duplicates.map((item)=><div key={item.id} className="rounded-xl border p-3 text-sm dark:border-slate-800"><div className="font-medium">{item.reasons.join(", ")}</div><div className="mt-1 text-xs text-slate-500">Confidence {Math.round(Number(item.score)*100)}%</div>{!item.resolution&&<div className="mt-3 flex flex-wrap gap-3"><button className="text-xs font-medium text-indigo-600" onClick={()=>invoke(()=>resolveDuplicate(item.id,"replace"))}>Replace existing</button><button className="text-xs font-medium text-emerald-600" onClick={()=>invoke(()=>resolveDuplicate(item.id,"keep_both"))}>Keep both</button><button className="text-xs font-medium text-slate-500" onClick={()=>invoke(()=>resolveDuplicate(item.id,"ignore"))}>Ignore</button></div>}</div>)}</div></section></div>}
      </>}
    </div>
  </div>;
}
