import { getActiveCompany } from "@/lib/auth";
import { createSavedReport, generateSavedReport } from "@/app/dashboard/analytics/actions";

export default async function ReportsPage(){
 const {supabase,company}=await getActiveCompany();
 if(!company) return <div>No active company.</div>;
 const {data:reports}=await supabase.from("saved_reports").select("*").eq("company_id",String(company.id)).order("updated_at",{ascending:false});
 return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Reports</h1><p className="text-sm text-slate-500">Create repeatable management reports from live company data.</p></div>
 <form action={createSavedReport} className="grid gap-3 rounded-2xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-950 md:grid-cols-4"><input name="name" required placeholder="Report name" className="rounded-xl border bg-transparent px-3 py-2 dark:border-slate-700"/><input name="description" placeholder="Description" className="rounded-xl border bg-transparent px-3 py-2 dark:border-slate-700 md:col-span-2"/><select name="period" className="rounded-xl border bg-transparent px-3 py-2 dark:border-slate-700"><option value="7_days">7 days</option><option value="30_days">30 days</option><option value="90_days">90 days</option><option value="6_months">6 months</option><option value="12_months">12 months</option><option value="year_to_date">Year to date</option><option value="all_time">All time</option></select><button className="rounded-xl bg-indigo-600 px-4 py-2 font-semibold text-white md:col-span-4">Create report</button></form>
 <div className="grid gap-4">{(reports??[]).map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-950"><div><div className="font-semibold">{r.name}</div><div className="text-sm text-slate-500">{r.description||"No description"} · {String(r.period).replaceAll("_"," ")} · {r.status}</div>{r.generated_at&&<div className="mt-1 text-xs text-slate-400">Generated {new Date(r.generated_at).toLocaleString()}</div>}</div><form action={generateSavedReport.bind(null,r.id)}><button className="rounded-xl border px-4 py-2 text-sm font-semibold dark:border-slate-700">{r.status==="ready"?"Regenerate":"Generate"}</button></form></div>)}{!reports?.length&&<div className="rounded-2xl border border-dashed p-10 text-center text-sm text-slate-500">No saved reports yet.</div>}</div></div>
}
